### ISSUE TITLE
Fix site url

### ISSUE THREAD

**Issue by Firefishy** [osmbe/sotm-eu-2023#1]
https://github.com/osmbe/sotm-eu-2023/blob/7961865e0956587d26f55fd6f6cad65bf9470df9/_config.yml#L5

The site url is currently hardcoded and needs to be fixed.

**Comment by Firefishy** [comment]
The `url` should be `stateofthemap.eu` you then need to set the same URL in github pages custom domain URL in repo settings.

**Comment by tomhughes** [comment]
There's a lot more than that in `_config.yml` that needs fixing...

**Comment by jbelien** [comment]
URL has been fixed.
For now, I've just forked the SotM'22 website, we didn't have time to update the website yet but we'll take care of it ASAP.
