### ISSUE TITLE
Add GeoPostcodes to bronze sponsors

### ISSUE THREAD

**Issue by marjanvandekauter-tomtom** [osmbe/sotm-eu-2023#112]

**Comment by jbelien** [comment]
@marjanvandekauter-tomtom Could you provide logo and URL ? Thanks.

**Comment by marjanvandekauter-tomtom** [comment]
> @marjanvandekauter-tomtom Could you provide logo and URL ? Thanks.

I created a pull request to add the logo to this repo: https://github.com/osmbe/sotm-eu-2023/pull/117
URL: https://www.geopostcodes.com/
