### ISSUE TITLE
Add the reservation link from the Crowne Plaza Antwerp in the accommodation section

### ISSUE THREAD

**Issue by Lauravdblom** [osmbe/sotm-eu-2023#118]

**Comment by marjanvandekauter-tomtom** [comment]
@Lauravdblom is this the right link: https://www.crowneplaza.com/redirect?path=hd&brandCode=CP&localeCode=en&regionCode=1&hotelCode=anrbe&_PMID=99801505&GPC=T10&cn=no&viewfullsite=true ?

**Comment by Lauravdblom** [comment]
This is the link they gave me:  https://www.ihg.com/crowneplaza/hotels/us/en/antwerp/anrbe/hoteldetail?fromRedirect=true&qSrt=sBR&qIta=99801505&icdv=99801505&qSlH=anrbe&qGrpCd=T10&setPMCookies=true&qSHBrC=CP&qDest=Gerard%20Legrellelaan%2010%2C%20Antwerp%2C%20BE&srb_u=1

**Comment by marjanvandekauter-tomtom** [comment]
This issue is not yet fixed. "Crowne Plaza Antwerp" has the link, but it also needs to be added to the text "this link".
