### ISSUE TITLE
Add Toerisme Vlaanderen as supporter sponsor

### ISSUE THREAD

**Issue by marjanvandekauter-tomtom** [osmbe/sotm-eu-2023#141]
Add Toerisme Vlaanderen to Supporter section of sponsor list

**Comment by jbelien** [comment]
No worries!
Could you provide the logo and URL ? Thanks.

**Comment by marjanvandekauter-tomtom** [comment]
@jbelien the URL is www.toerismevlaanderen.be
No logo needed because we only list the names of the supporter sponsors.

Thanks for your help!
