### ISSUE TITLE
Add the FAQs - State of the Map Europe 2023 PDF to the 'Program' tab

### ISSUE THREAD

**Issue by DaniDaubaras** [osmbe/sotm-eu-2023#150]
Edits can be made to the 'Program' tab to include a link to our FAQs. PDF attached here. The copy can be updated to the following:

_____

The conference will be packed with great talks, workshops and opportunities to meet and network with the OpenStreetMap community. Checkout our program below and have a look at the State of the Map Europe 2023 - FAQs for any questions you may have.

**Comment by DaniDaubaras** [comment]
[State of the Map Europe 2023 FAQs.pdf](https://github.com/osmbe/sotm-eu-2023/files/13165742/State.of.the.Map.Europe.2023.FAQs.pdf)

**Comment by jbelien** [comment]
Just a question: should we use a web page instead of a PDF for the FAQ ?
It would be easier to update.

**Comment by DaniDaubaras** [comment]
Hi Jonathan,

Yes, here is a link to the original file<https://docs.google.com/document/d/1zUmzvpcCz9NlItkVF3J7_0OlskjBIzbPiLkSCHW5Wbs/edit?usp=sharing> (in case you need it).

Thanks,
Dani

From: Jonathan Beliën ***@***.***>
Date: Wednesday, 25 October 2023 at 15:17
To: osmbe/sotm-eu-2023 ***@***.***>
Cc: Danielle Daubaras ***@***.***>, Author ***@***.***>
Subject: Re: [osmbe/sotm-eu-2023] Add the FAQs - State of the Map Europe 2023 PDF to the 'Program' tab (Issue #150)

Just a question: could we use a web page instead of a PDF for the FAQ ?
It would be easier to update.

**Comment by DaniDaubaras** [comment]
Hi @jbelien would it be possible to get this update online today?

**Comment by DaniDaubaras** [comment]
Hi @jbelien,

Can you help to update the FAQ link to the link to this new PDF attached? 

Thank you!

Dani

[State of the Map Europe 2023 - FAQs .pdf](https://github.com/osmbe/sotm-eu-2023/files/13297073/State.of.the.Map.Europe.2023.-.FAQs.pdf)

**Comment by jbelien** [comment]
@DaniDaubaras Done in 632f3e46b8e3c152bfdade1146bb83b1e338668b
