### ISSUE TITLE
Create first version based on branding package

### ISSUE THREAD

**Issue by xivk** [osmbe/sotm-eu-2023#17]
We will receive very soon a branding package. I will link it here.

**Comment by bobleegogogo** [comment]
Hi @xivk, here is Hao. Would the branding package be similar to previous version of SOTM (e.g., https://2022.stateofthemap.org/)? As we need to create a webpage for OSM Science 2023 (previous academic track), I want to know shall we want until we have the branding package to create the webpage or just go ahead for now. Thanks

**Comment by spatialscientist** [comment]
Hi @bobleegogogo, I think @xivk as shared the branding package [here](https://github.com/osmbe/sotm-eu-2023/blob/main/assets/SotmEU_Sponsorship_Packet.pdf). Best wishes

**Comment by jbelien** [comment]
@bobleegogogo I've just uplaoded fonts, logos, icons, and branding overview. 👍

**Comment by jbelien** [comment]
🚀 Deployed: https://stateofthemap.eu/
