### ISSUE TITLE
OSM Science 2023 webpage

### ISSUE THREAD

**Issue by bobleegogogo** [osmbe/sotm-eu-2023#18]
**Aim**: create the webpage for OSM Science 2023

The OSM science organizer team has got a pretalx instance for managing the submission. In addition, the Call For Papers (CFP) are drafted. Now we need a website page under https://stateofthemap.eu/ to direct people to the CFP and pretalx submission system.

Any suggestions how to best structure the pull request would be highly appreciated

**Comment by bobleegogogo** [comment]
> @bobleegogogo I've just uploaded fonts, logos, icons, and branding overview. 👍

Thank you, @jbelien! I can see the branding overview now.

I think it is better to continue the discussion here as the goal for us is to create the webpage for OSM Science 2023, similar to what we have here: https://2022.stateofthemap.org/calls/academic/. I see that SOTMEU currently have a different structure than SOTM2022, therefore I am not sure how exactly we can set up such a call with under which page and with which style?

Any suggestions or tips would be highly appreciated.

**Comment by jbelien** [comment]
@bobleegogogo I'll try to create an initial structure this weekend. I'll keep you updated.

But if you want to already start working on it right now, you can already upload a Markdown file with your content or even better a React/Next page in `src/pages`, I'll make it work.

**Comment by bobleegogogo** [comment]
Hi @jbelien, thank you for the timely response! If we have the initial structure after this week, it would be great. I would work on the Markdown locally for now.

**Comment by jbelien** [comment]
Link to add to SotMEU website: https://osmscience.github.io/OSMScience2023/

**Comment by bobleegogogo** [comment]
thanks for adding the OSMScience page @jbelien
