### ISSUE TITLE
Add call for papers to the website.

### ISSUE THREAD

**Issue by xivk** [osmbe/sotm-eu-2023#48]
We need to add the call for papers to the website. We are using pretalx for this and should integrate this into the website codebase.

**Comment by jbelien** [comment]
No worries, the link to add is here: https://pretalx.com/state-of-the-map-europe-2023/cfp
But we need to set the event as public first, I think.

**Comment by xivk** [comment]
Add a submit your talk button on the top-left:

<img width="772" alt="image" src="https://github.com/anyways-open/impact-frontend/assets/1128068/bfd6afa3-63ee-4cfa-b200-670f65883a18">

Similar to what's in the template: https://keynote.tailwindui.com/#

**Comment by jbelien** [comment]
Definitely not an issue 👍 
What should it link to ? Do you already have the URL ?

**Comment by xivk** [comment]
Hey can you also give me some hint @jbelien about the <ul> and <li> styling? 

Here: https://deploy-preview-56--whimsical-buttercream-efd44b.netlify.app/call-for-participation

There are no bullet points showing up, very annoying.

**Comment by xivk** [comment]
Also the link is `/call-for-participation)`

**Comment by jbelien** [comment]
> Hey can you also give me some hint @jbelien about the `<ul>` and `<li>` styling?

https://tailwindcss.com/docs/list-style-type
