### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by xivk** [osmbe/sotm-eu-2023#60]
We need to add a code of conduct page to the website to reference in the call for papers.

**Comment by DaniDaubaras** [comment]
Quick link to CoC: https://docs.google.com/document/d/1AKGZqcqS7un9AcCSxzHN8EJmVMgZF1XYfd72VAA20KI/edit?usp=sharing

**Comment by jbelien** [comment]
@DaniDaubaras Thank you! I've requested access to the file.

**Comment by DaniDaubaras** [comment]
Sent! Let me know if you have any challenges accessing any others.

> Danielle Daubaras  /  Senior Global Events Manager  / ***@***.******@***.***>  / +31 (0)6 1989 0558


From: Jonathan Beliën ***@***.***>
Date: Saturday, 8 July 2023 at 20:47
To: osmbe/sotm-eu-2023 ***@***.***>
Cc: Danielle Daubaras ***@***.***>, Mention ***@***.***>
Subject: Re: [osmbe/sotm-eu-2023] Add code of conduct (Issue #60)

@DaniDaubaras<https://github.com/DaniDaubaras> Thank you! I've requested access to the file.

**Comment by xivk** [comment]
@DaniDaubaras The code of conduct is now live on the website. I'll try and work on the call for papers later today to finish it. I'm supposed to have a week off but I'll do my best ;)

**Comment by DaniDaubaras** [comment]
@xivk looks great! We are working to update the pptx. for the call tomorrow and will share the update from the venue as well.

Things we'd like to discuss tomorrow afternoon:

- Venue / payment
- Sponsorship status
- OSMScience

Don't work too hard on your holidays! ;)
