### ISSUE TITLE
Add some type of menu/site map

### ISSUE THREAD

**Issue by xivk** [osmbe/sotm-eu-2023#70]
I want people to have immediate access to call for papers and code of conduct. Not the code of conduct is only visible in the footer. 

Is it possible to add some type of menu or navigation somehow?

We will also need this for other stuff like the program later on and other things like advice on hotels/antwerp/where to sleep. How to get to the conference etc etc. The website is going to grow and become too complex for a one-pager.

**Comment by jbelien** [comment]
Shouldn't be an issue ; I'll try to give it a go this week.

**Comment by xivk** [comment]
@jbelien perhaps we don't need this if we stay true to the original template but we need to add a logo on top left to jump back home
